# Generated by Django 2.2.8 on 2019-12-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_column='user_name', max_length=20)),
                ('email', models.EmailField(db_column='email', max_length=30)),
                ('passwd', models.CharField(db_column='passwd', max_length=20)),
                ('img', models.CharField(db_column='img', max_length=20)),
                ('jobs', models.CharField(db_column='jobs', max_length=20)),
                ('entry_time', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
